"use client";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { useState } from "react";

const inter = Outfit({ subsets: ["latin"] });
import { UserDetailContext } from "./_context/UserDetailContext";
// import {Toaster} from '../components/ui/toaster'
import {Toaster} from '../components/ui/toaster'

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [userDetail, setUserDetail] = useState();
  return (
    <ClerkProvider>
      <UserDetailContext.Provider value={{ userDetail, setUserDetail }}>
        <html lang="en">
          <body className={inter.className}>
            {children}
            <Toaster />
          </body>
        </html>
      </UserDetailContext.Provider>
    </ClerkProvider>
  );
}
